Домашнее задание №1
AnnieKhrush/2022-2-VK-EDU-FS-Frontend-A-Khrushkova pull request #1
Opened 2022-10-06 19:31 UTC by AnnieKhrush

# Домашнее задание № 1

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
* Реализованы все 3 функции
* Написан тест на функцию convertBytesToHuman
*

2022-10-10 20:24 UTC, martinkomitsky commented on my-project/package.json
> +    "ansi-escapes": "^4.3.2",
Откуда у тебя этот список зависимостей появился? В ДЗ этого не требовалось

2022-10-10 20:24 UTC, martinkomitsky requested changes
Оставить только нужные зависимости для ДЗ

2022-10-11 09:36 UTC, AnnieKhrush commented on my-project/package.json
> +    "ansi-escapes": "^4.3.2",
Добрый день! Я исправила файл package.json, можете проверить, пожалуйста? Список зависимостей создался сам при генерации проекта.

2022-10-13 12:01 UTC, martinkomitsky commented on my-project/package.json
> +    "ansi-escapes": "^4.3.2",
очень странно, такого не должно было произойти...

2022-10-13 12:02 UTC, martinkomitsky approved these changes
12

2022-10-13 12:02 UTC, merged